### ISSUE TITLE
服务器配置代理

### ISSUE THREAD

**Issue by kexiaobin11** [yunzhiclub/integration-testing#98]
为了使用从github拉取导致的网络问题

**Comment by teacherpan** [comment]
信息描述的不够具体。

**Comment by teacherpan** [comment]
![image](https://github.com/yunzhiclub/integration-testing/assets/12424383/1b92204e-8df0-4403-bcbb-dfa3bfc11b4a)
这种问题说明是网络问题，所以我们要做的是为机器人配置相关的代理。

在liunx中，代理可以通过设置环境变量来解决的。文档在这：https://docs.github.com/en/actions/learn-github-actions/variables

所以解决的方法就是：
1. 在机器人中局域网中安装一个代理服务，通过该代理服务可以访问外网
2. 为机器人设置相关的代理变量，这样机器人就可以走代理了

其实在 CD 中，self-host的机器人完成应该是：下载打包后的文件并进行部署的操作。所以个人感觉可以用不着checkout代码，而是直接下载 前置机器人打包后的包。

比如可能是这样：
1. angular机器人打包，然后上传
2.  spring boots机器人找包，上传
3. 此时才是自有机器人上场，进行包的下载，然后完成部署。

**Comment by teacherpan** [comment]
当前代理环境已经准备到位，启用示例：
```yml
on:
  workflow_dispatch


jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          https_proxy: http://192.168.10.5:7890
          http_proxy: http://192.168.10.5:7890
          all_proxy: socks5://192.168.10.5:7890
```

在上述配置的env中进行环境变量的设置，该设置仅对当前 greeting_job 生效。
将上述env中的三条信息添加到机器人命令中即可。
